server:
  port: 8080
  error:
    path: "/error"

myapp:
  config:
    prop: 1
    filters:
      filter-num: 1
      name-filters:
        - "guest"
        - "nonguest"

endpoints:
  enabled: true

spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - base64
  datasource:
    url: "jdbc:postgresql://127.0.0.1/database"
    username: "admin"
    password: "admin"
  application:
    name: "Spring Boot Example"

logging:
  level:
    org.springframework: debug
    ru.innopolis.stc: debug
